# Generated by Django 2.2.3 on 2019-08-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='Please enter a description!'),
            preserve_default=False,
        ),
    ]
