# Generated by Django 2.1.5 on 2019-02-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link_hot',
            new_name='link_host',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
