# Generated by Django 2.1.5 on 2019-02-26 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190226_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
