# Generated by Django 2.1.5 on 2019-02-26 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190226_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
