# Generated by Django 2.1.5 on 2019-03-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20190307_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.Project'),
        ),
    ]
