# Generated by Django 2.1.5 on 2019-03-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20190308_0526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name_plural': 'CVs'},
        ),
        migrations.AlterField(
            model_name='cv',
            name='document',
            field=models.FileField(upload_to='cv/', verbose_name='CV'),
        ),
    ]
