# Generated by Django 2.1.7 on 2019-03-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20190308_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
