# Generated by Django 2.2.13 on 2020-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20190801_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_more',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
